"""soft_deletes

Revision ID: 85037413bcdb
Revises: a68c6bb2972c
Create Date: 2023-11-16 23:12:39.412182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85037413bcdb'
down_revision = 'a68c6bb2972c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('union_member', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('union_member', 'is_deleted')
    op.alter_column('file', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
