"""add soft delete

Revision ID: 90539e2253b3
Revises: a68c6bb2972c
Create Date: 2025-06-01 17:29:08.641697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90539e2253b3'
down_revision = 'a68c6bb2972c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('union_member', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('union_member', 'is_deleted')
    op.alter_column('file', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
