"""Add is_deleted field to UnionMember table

Revision ID: dddf1cc0c593
Revises: a68c6bb2972c
Create Date: 2024-10-19 19:49:20.361627

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'dddf1cc0c593'
down_revision = 'a68c6bb2972c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'source', existing_type=sa.VARCHAR(), nullable=False)
    op.add_column('union_member', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute(f'UPDATE "union_member" SET  is_deleted = False')
    op.alter_column('union_member', sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('union_member', 'is_deleted')
    op.alter_column('file', 'source', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
