name: Python package

on:
  pull_request:


jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up docker
        uses: docker-practice/actions-setup-docker@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements.dev.txt
      - name: Run postgres
        run: |
          make db
      - name: Migrate DB
        run: |
          make migrate
      - name: Run redis
        run: |
          make redis
      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=print_service tests > pytest-coverage.txt
      - name: Print report
        if: always()
        run: |
          cat pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
